name: tests

on:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT_SUBMODULE }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: bun test
